<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_rumah_model extends CI_Model
{

    public $table = 'tbl_rumah';
    public $id = 'id_rumah';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('tbl_komplek', 'tbl_komplek.id_komplek = tbl_rumah.id_komplek');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_rumah_asc()
    {
        $this->db->join('tbl_komplek', 'tbl_komplek.id_komplek = tbl_rumah.id_komplek');
        $this->db->where('status', '0');
        $this->db->order_by('tbl_komplek.id_komplek', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('tbl_komplek', 'tbl_komplek.id_komplek = tbl_rumah.id_komplek');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_rumah', $q);
        $this->db->or_like('id_komplek', $q);
        $this->db->or_like('blok', $q);
        $this->db->or_like('nomer', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_rumah', $q);
        $this->db->or_like('id_komplek', $q);
        $this->db->or_like('blok', $q);
        $this->db->or_like('nomer', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    public function is_duplicate($id_komplek, $blok, $nomer)
    {
        $this->db->where('id_komplek', $id_komplek);
        $this->db->where('blok', $blok);
        $this->db->where('nomer', $nomer);
        $query = $this->db->get('tbl_rumah');

        return $query->num_rows() > 0;
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_rumah_model.php */
/* Location: ./application/models/Tbl_rumah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-07-24 04:59:00 */
/* http://harviacode.com */